server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false    #表示不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    eureka-server-read-timeout-seconds: 10
    eureka-server-connect-timeout-seconds: 10
